# prometheus global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "prometheus.rules.yml"
  
scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ['node:9100']

#    basic_auth:
#      username: admin
#      password: kfWQG7Hs

# Blackbox-exporter
  - job_name: 'blackbox-exporter-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://k8s_dashboard.example.com/ 
        - http://ceph_dashboard.example.com/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: bbexporter_server_ip:9115

  - job_name: 'blackbox-exporter-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 8.8.8.8
        - 4.2.2.4
        - 1.1.1.2
        - 190.2.139.109
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: bbexporter_server_ip:9115

  - job_name: 'blackbox-exporter-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - 190.2.139.109:6261
        - 190.2.139.109:1723
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: bbexporter_server_ip:9115

# VMs node-exporter
  - job_name: vms-node-exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
    - targets: [ 'nginx_server_ip:9100' ]
      labels:
        hostname: 'Nginx'
    - targets: [ 'bbexporter_server_ip:9100' ]
      labels:
        hostname: 'BB-Exporter'
    - targets: [ 'grafana_server_iop:9100' ]
      labels:
        hostname: 'Grafana'
